"""Digital twin of the integrated ATPE + PCMRITMS series-hybrid powertrain.

Pure standard-library implementation (no third-party dependencies).

Public API:
    build_default_twin()  -> Powertrain  (Phase-1 MUV/SUV configuration)
    build_performance_twin() -> Powertrain (Phase-2 performance configuration)
    run(twin, cycle)      -> Result
    DriveCycles           -> synthetic drive-cycle factory
"""

from typing import Callable

from .config import (
    TierSpec,
    SingleCylinderGate1Config,
    ATPEConfig,
    BufferConfig,
    BatteryConfig,
    BatteryThermalConfig,
    VehicleConfig,
    ControlConfig,
    TractionConfig,
    TwinConfig,
    BodyStyle,
    PHASE1_BODIES,
    phase1_config,
    phase1_config_for,
    phase1_variants,
    with_battery_thermal,
    with_dc_link,
    with_gate1,
    with_phoenix_v3,
    phase2_config,
)
from .dc_link import DcLink, DcLinkConfig, DcLinkTelemetry, default_phase1_dc_link
from .gate1_residuals import (
    GATE1_RIG_CSV_COLUMNS,
    Gate1RigRow,
    ResidualReport,
    compare_row_to_twin,
    read_gate1_rig_csv,
    run_gate1_residual_report,
    synthesize_gate1_rig_csv,
    write_gate1_rig_csv,
)
from .single_cylinder import (
    SingleCylinderInputs,
    SingleCylinderResult,
    PressureTrace,
    FreePistonConfig,
    FreePistonResult,
    Gate1Point,
    Gate1BenchTargets,
    Gate1BenchMeasurement,
    Gate1BenchResult,
    PHOENIX_X12_STROKE_MM,
    simulate_1d_combustion,
    simulate_free_piston,
    gate1_point_from_load,
    gate1_bench_at_load,
)
from .powertrain import Powertrain
from .controller import UnifiedController, ClosedLoopRotorController, ControlState
from .drive_cycles import DriveCycles, DriveCycle
from .simulation import run, Result, StepRecord
from .pcmritms_rotor import (
    RotorSet,
    TorqueModulationResult,
    simulate_torque_augmentation,
)
from .pcmritms_coupling import (
    couple_buffer,
    rotor_peak_reaction_torque_nm,
    rotor_transient_power_w,
)
from .fleet import (
    FleetCell,
    standard_cycles,
    charge_sustaining_bodies,
    stress_bodies,
    closed_loop_rotor_bodies,
    stress_unmet_launch_kj,
    run_fleet,
    fleet_table,
    fleet_report,
    fleet_delta,
)
from .acceptance import (
    ERSTargets,
    Check,
    evaluate,
    report,
    report_bodies,
    compare_bodies,
    recommend_motor,
    recommend_motors,
    MotorRecommendation,
    SweepPoint,
    sweep_motor,
    sweep_grid,
    sweep_body_detail,
    phase1_targets,
    phase1_targets_for,
    phase1_body_targets,
)
from .validation import (
    Parameter,
    Elasticity,
    phase1_sensitivity_params,
    elasticity,
    sensitivity_table,
    sensitivity_report,
    capability_sweep,
    capability_report,
)
from .economics import (
    EconomicsConfig,
    TcoResult,
    DEFAULT_USAGE_MIX,
    tco_for_body,
    fleet_tco,
    tco_table,
)
from .sizing import (
    SizingConfig,
    SizingPoint,
    BodySizing,
    size_battery_power,
    fleet_battery_sizing,
    sizing_table,
)
from .montecarlo import (
    Distribution,
    TcoBands,
    DEFAULT_PARAM_SIGMA,
    DEFAULT_ECON_SIGMA,
    monte_carlo_fuel,
    monte_carlo_tco,
    fleet_uncertainty,
    uncertainty_table,
)
from .ambient import (
    AmbientConfig,
    AmbientPoint,
    AmbientSweep,
    DEFAULT_TEMPS_C,
    air_density_factor,
    hvac_load_w,
    simulate_at_temp,
    ambient_sweep,
    fleet_ambient,
    ambient_table,
)
from .regulatory_cycles import (
    CycleStats,
    CycleSpec,
    RegulatoryCycle,
    RegulatoryCycles,
    RegulatoryEconomy,
    cycle_stats,
    regulatory_fidelity_table,
    regulatory_economy,
    fleet_regulatory,
    regulatory_economy_table,
)
from .summary import (
    BodySummary,
    ExecutiveSummary,
    build_executive_summary,
)
from .coldstart import (
    ColdStartConfig,
    ColdStartResult,
    cold_start_for,
    fleet_cold_start,
    cold_start_table,
)
from .payload import (
    LoadConfig,
    LoadPoint,
    LoadSweep,
    OCCUPANT_KG,
    payload_sweep,
    fleet_payload,
    payload_table,
)
from .phev import (
    GridConfig,
    PhevResult,
    phev_for_body,
    fleet_phev,
    phev_table,
)
from .degradation import (
    DegradationConfig,
    DegradationPoint,
    DegradationCurve,
    degradation_for,
    fleet_degradation,
    degradation_table,
)
from .ice_benchmark import (
    benchmark_summary,
    wltp_benchmark,
    run_ice_fleet,
)
from .graceful_degradation import (
    DegradedScenario,
    DegradedBodyResult,
    atpe_with_cylinder_offline,
    evaluate_degraded_body,
    fleet_graceful_degradation,
    graceful_degradation_table,
)
from .gate1_matrix import (
    Gate1MatrixCell,
    Gate1MatrixSummary,
    Gate1VehicleComparison,
    run_gate1_matrix,
    gate1_bench_uncertainty,
    gate1_vehicle_fuel_comparison,
    gate1_matrix_table,
    gate1_matrix_report,
    gate1_matrix_csv_rows,
    write_gate1_matrix_csv,
    GATE1_MATRIX_CSV_COLUMNS,
    DEFAULT_SPEED_RPM,
    DEFAULT_LOAD_FRACTIONS,
    SWEET_SPOT_TIER_INDEX,
)
from .misfire import (
    MisfireCoverageResult,
    MisfireSpec,
    apply_misfire,
    gate1_bench_with_misfire,
    run_misfire_coverage,
)
from .gate4_scaling import (
    CylinderLayout,
    Gate4LayoutResult,
    Gate4ScalingSummary,
    REFERENCE_LAYOUT,
    CANONICAL_X12_LAYOUT,
    DEFAULT_RING_SIZES,
    STORYBOARD_CARTRIDGE_KW,
    RATING_PROFILES,
    build_atpe_from_layout,
    build_x12_homogeneous_atpe,
    charge_sustaining_fuel_config,
    enumerate_layouts,
    enumerate_ring_layouts,
    ring_label,
    layout_tier_mix_kind,
    is_design_aligned,
    count_active_tiers,
    is_all_three_tiers,
    evaluate_layout,
    run_gate4_sweep,
    run_ring_size_study,
    run_x12_ring_sweep,
    run_full_gate4_study,
    gate4_scaling_table,
    gate4_ring_sweet_spot_table,
    gate4_tier_architecture_table,
    gate4_scaling_report,
    gate4_csv_rows,
    write_gate4_scaling_csv,
    write_gate4_tier_advantage_csv,
    build_tier_architecture_comparison,
    GATE4_CSV_COLUMNS,
    TIER_ADVANTAGE_CSV_COLUMNS,
)

__all__ = [
    "TierSpec",
    "SingleCylinderGate1Config",
    "ATPEConfig",
    "BufferConfig",
    "BatteryConfig",
    "BatteryThermalConfig",
    "VehicleConfig",
    "ControlConfig",
    "TractionConfig",
    "TwinConfig",
    "BodyStyle",
    "PHASE1_BODIES",
    "phase1_config",
    "phase1_config_for",
    "phase1_variants",
    "with_battery_thermal",
    "with_dc_link",
    "with_gate1",
    "DcLink",
    "DcLinkConfig",
    "DcLinkTelemetry",
    "default_phase1_dc_link",
    "GATE1_RIG_CSV_COLUMNS",
    "Gate1RigRow",
    "ResidualReport",
    "compare_row_to_twin",
    "read_gate1_rig_csv",
    "run_gate1_residual_report",
    "synthesize_gate1_rig_csv",
    "write_gate1_rig_csv",
    "phase2_config",
    "SingleCylinderInputs",
    "SingleCylinderResult",
    "PressureTrace",
    "FreePistonConfig",
    "FreePistonResult",
    "Gate1Point",
    "simulate_1d_combustion",
    "simulate_free_piston",
    "gate1_point_from_load",
    "Powertrain",
    "UnifiedController",
    "ClosedLoopRotorController",
    "ControlState",
    "DriveCycles",
    "DriveCycle",
    "run",
    "Result",
    "StepRecord",
    "RotorSet",
    "TorqueModulationResult",
    "simulate_torque_augmentation",
    "couple_buffer",
    "rotor_peak_reaction_torque_nm",
    "rotor_transient_power_w",
    "FleetCell",
    "standard_cycles",
    "charge_sustaining_bodies",
    "stress_bodies",
    "closed_loop_rotor_bodies",
    "stress_unmet_launch_kj",
    "run_fleet",
    "fleet_table",
    "fleet_report",
    "fleet_delta",
    "ERSTargets",
    "Check",
    "evaluate",
    "report",
    "report_bodies",
    "compare_bodies",
    "recommend_motor",
    "recommend_motors",
    "MotorRecommendation",
    "SweepPoint",
    "sweep_motor",
    "sweep_grid",
    "sweep_body_detail",
    "phase1_targets",
    "phase1_targets_for",
    "phase1_body_targets",
    "Parameter",
    "Elasticity",
    "phase1_sensitivity_params",
    "elasticity",
    "sensitivity_table",
    "sensitivity_report",
    "capability_sweep",
    "capability_report",
    "EconomicsConfig",
    "TcoResult",
    "DEFAULT_USAGE_MIX",
    "tco_for_body",
    "fleet_tco",
    "tco_table",
    "SizingConfig",
    "SizingPoint",
    "BodySizing",
    "size_battery_power",
    "fleet_battery_sizing",
    "sizing_table",
    "Distribution",
    "TcoBands",
    "DEFAULT_PARAM_SIGMA",
    "DEFAULT_ECON_SIGMA",
    "monte_carlo_fuel",
    "monte_carlo_tco",
    "fleet_uncertainty",
    "uncertainty_table",
    "AmbientConfig",
    "AmbientPoint",
    "AmbientSweep",
    "DEFAULT_TEMPS_C",
    "air_density_factor",
    "hvac_load_w",
    "simulate_at_temp",
    "ambient_sweep",
    "fleet_ambient",
    "ambient_table",
    "CycleStats",
    "CycleSpec",
    "RegulatoryCycle",
    "RegulatoryCycles",
    "RegulatoryEconomy",
    "cycle_stats",
    "regulatory_fidelity_table",
    "regulatory_economy",
    "fleet_regulatory",
    "regulatory_economy_table",
    "BodySummary",
    "ExecutiveSummary",
    "build_executive_summary",
    "ColdStartConfig",
    "ColdStartResult",
    "cold_start_for",
    "fleet_cold_start",
    "cold_start_table",
    "LoadConfig",
    "LoadPoint",
    "LoadSweep",
    "OCCUPANT_KG",
    "payload_sweep",
    "fleet_payload",
    "payload_table",
    "GridConfig",
    "PhevResult",
    "phev_for_body",
    "fleet_phev",
    "phev_table",
    "DegradationConfig",
    "DegradationPoint",
    "DegradationCurve",
    "degradation_for",
    "fleet_degradation",
    "degradation_table",
    "benchmark_summary",
    "wltp_benchmark",
    "run_ice_fleet",
    "DegradedScenario",
    "DegradedBodyResult",
    "atpe_with_cylinder_offline",
    "evaluate_degraded_body",
    "fleet_graceful_degradation",
    "graceful_degradation_table",
    "Gate1MatrixCell",
    "Gate1MatrixSummary",
    "Gate1VehicleComparison",
    "run_gate1_matrix",
    "gate1_bench_uncertainty",
    "gate1_vehicle_fuel_comparison",
    "gate1_matrix_table",
    "gate1_matrix_report",
    "gate1_matrix_csv_rows",
    "write_gate1_matrix_csv",
    "GATE1_MATRIX_CSV_COLUMNS",
    "DEFAULT_SPEED_RPM",
    "MisfireCoverageResult",
    "MisfireSpec",
    "apply_misfire",
    "gate1_bench_with_misfire",
    "run_misfire_coverage",
    "DEFAULT_LOAD_FRACTIONS",
    "SWEET_SPOT_TIER_INDEX",
    "CylinderLayout",
    "Gate4LayoutResult",
    "Gate4ScalingSummary",
    "REFERENCE_LAYOUT",
    "CANONICAL_X12_LAYOUT",
    "DEFAULT_RING_SIZES",
    "STORYBOARD_CARTRIDGE_KW",
    "RATING_PROFILES",
    "build_atpe_from_layout",
    "build_x12_homogeneous_atpe",
    "charge_sustaining_fuel_config",
    "enumerate_layouts",
    "enumerate_ring_layouts",
    "ring_label",
    "layout_tier_mix_kind",
    "is_design_aligned",
    "count_active_tiers",
    "is_all_three_tiers",
    "evaluate_layout",
    "run_gate4_sweep",
    "run_ring_size_study",
    "run_x12_ring_sweep",
    "run_full_gate4_study",
    "gate4_scaling_table",
    "gate4_ring_sweet_spot_table",
    "gate4_tier_architecture_table",
    "gate4_scaling_report",
    "gate4_csv_rows",
    "write_gate4_scaling_csv",
    "write_gate4_tier_advantage_csv",
    "build_tier_architecture_comparison",
    "GATE4_CSV_COLUMNS",
    "TIER_ADVANTAGE_CSV_COLUMNS",
    "Gate1BenchTargets",
    "Gate1BenchMeasurement",
    "Gate1BenchResult",
    "gate1_bench_at_load",
    "PHOENIX_X12_STROKE_MM",
    "build_default_twin",
    "build_gate1_twin",
    "build_phoenix_v3_twin",
    "build_dynamic_ring_twin",
    "build_performance_twin",
    "build_body_twins",
]


def build_default_twin(rotor_coupled: bool = False) -> Powertrain:
    """Return a Powertrain configured for the Phase-1 petrol MUV/SUV."""
    return Powertrain(phase1_config(rotor_coupled=rotor_coupled))


def build_gate1_twin(
    rotor_coupled: bool = False,
    *,
    prefer_cantera: bool = False,
    reference_speed_rpm: float = 2600.0,
) -> Powertrain:
    """Phase-1 SUV twin with Gate 1 physics-derived tier efficiencies enabled."""
    return Powertrain(with_gate1(
        phase1_config(rotor_coupled=rotor_coupled),
        prefer_cantera=prefer_cantera,
        reference_speed_rpm=reference_speed_rpm,
    ))


def build_phoenix_v3_twin(
    rotor_coupled: bool = False,
    *,
    tuning_path: str | None = None,
    v3_cycles: int = 24,
) -> Powertrain:
    """Phase-1 SUV twin with Phoenix V3 cartridge physics for ATPE tiers."""
    return Powertrain(with_phoenix_v3(
        phase1_config(rotor_coupled=rotor_coupled),
        tuning_path=tuning_path,
        v3_cycles=v3_cycles,
    ))


def build_dynamic_ring_twin(
    rotor_coupled: bool = False,
    *,
    probe_cycles: int = 6,
    fast_probe: bool = True,
    pcmritms_brain_enabled: bool = True,
    closed_loop_surge: bool = True,
) -> Powertrain:
    """Phase-1 SUV twin with Gate-5 dynamic ring cartridge dispatch."""
    from .config import with_dynamic_ring

    return Powertrain(with_dynamic_ring(
        phase1_config(rotor_coupled=rotor_coupled),
        probe_cycles=probe_cycles,
        fast_probe=fast_probe,
        pcmritms_brain_enabled=pcmritms_brain_enabled,
        closed_loop_surge=closed_loop_surge,
    ))


def build_performance_twin() -> Powertrain:
    """Return a Powertrain configured for the Phase-2 performance vehicle."""
    return Powertrain(phase2_config())


def build_body_twins(
    rotor_coupled: bool = False,
) -> dict[str, Callable[[], Powertrain]]:
    """Return per-body Powertrain *builders* (callables) for every Phase-1 body.

    Each value is a zero-arg builder so capability sims can spin up fresh,
    independent twins on demand (their internal energy state is consumed).
    When `rotor_coupled` is True, every body's inertial buffer gains the
    PCMRITMS rotor-derived brief-burst discharge rating.
    """
    return {
        name: (lambda c=cfg: Powertrain(c))
        for name, cfg in phase1_variants(rotor_coupled=rotor_coupled).items()
    }
