"""Configuration dataclasses for the powertrain digital twin.

All values use SI base units unless a name carries an explicit unit suffix:
power in watts (W), energy in joules (J), mass in kilograms (kg), speed in m/s.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# --- Physical constants -----------------------------------------------------

GRAVITY = 9.81  # m/s^2
AIR_DENSITY = 1.225  # kg/m^3 at sea level, 15 C
GASOLINE_LHV_MJ_PER_KG = 43.4  # lower heating value
GASOLINE_DENSITY_KG_PER_L = 0.745
GASOLINE_CO2_KG_PER_L = 2.31  # tailpipe CO2 per litre burned


@dataclass(frozen=True)
class TierSpec:
    """A single ATPE cylinder tier (a group of identically sized cylinders)."""

    name: str
    units: int  # number of cylinders in this tier
    displacement_cc: float  # per-cylinder displacement
    max_electric_w: float  # total continuous electrical output of the tier
    thermal_efficiency: float  # fuel -> electrical conversion efficiency (0..1)


@dataclass(frozen=True)
class SingleCylinderGate1Config:
    """Optional Gate 1 single-cylinder model controls for ATPE tiers."""

    enabled: bool = False
    prefer_cantera: bool = True
    reference_speed_rpm: float = 2600.0


@dataclass(frozen=True)
class ATPEConfig:
    """Adaptive Torque & Power Engine: an ordered, additive stack of tiers."""

    tiers: tuple[TierSpec, ...]
    generator_efficiency: float = 0.96  # linear-generator piston->electrical eff
    # Maximum rate the electrical output can ramp (W per second). A real
    # free-piston generator cannot step from idle to full power instantly; the
    # PCMRITMS inertial buffer exists to bridge exactly this ramp. None = no
    # limit (instantaneous response, the optimistic default used for the
    # validated steady-cycle figures).
    max_slew_w_per_s: float | None = None
    # Optional Gate 1 physics-derived efficiency path.
    gate1: SingleCylinderGate1Config | None = None

    @property
    def max_electric_w(self) -> float:
        return sum(t.max_electric_w for t in self.tiers)

    def best_brake_thermal_efficiency(self) -> float:
        """Peak fuel->piston (brake thermal) efficiency across tiers.

        Tier efficiency is the bundled fuel->electrical figure, so the brake
        thermal component is recovered by removing the generator efficiency.
        """
        best_combined = max(t.thermal_efficiency for t in self.tiers)
        return best_combined / self.generator_efficiency


@dataclass(frozen=True)
class BufferConfig:
    """PCMRITMS inertial torque buffer as a bounded kinetic reservoir."""

    max_energy_j: float
    max_discharge_w: float
    max_charge_w: float
    round_trip_efficiency: float  # 0..1
    initial_fraction: float = 1.0  # start fully spun up
    # Optional brief-burst discharge rating from phase-coordinated rotor surge
    # (PCMRITMS). When set (>= max_discharge_w), the buffer may momentarily
    # exceed its continuous rating; the energy reservoir self-limits duration.
    # None = no rotor coupling (continuous rating is the only cap).
    peak_transient_w: float | None = None


@dataclass(frozen=True)
class BatteryConfig:
    """LFP traction battery used as buffer + EV-range store."""

    usable_capacity_j: float
    max_discharge_w: float
    max_charge_w: float
    soc_target: float  # charge-sustaining setpoint (0..1)
    soc_ev_floor: float  # below this, no EV-only operation
    initial_soc: float = 0.8
    # Optional lumped-thermal + power-derating model. None = thermodynamically
    # ideal pack (no I^2R heat, no temperature derating) - the optimistic
    # default used for the validated steady-cycle figures. Opt-in for the
    # durability/thermal-stress studies (see battery.py).
    thermal: "BatteryThermalConfig | None" = None
    # Cycle-life rating (equivalent full cycles to end-of-life). When set, the
    # runner projects a pack service life from the measured throughput. This is
    # a derived metric only - it never changes the physics, so it is safe to
    # leave populated on the default config.
    cycle_life_efc: float | None = None


@dataclass(frozen=True)
class BatteryThermalConfig:
    """Lumped single-node thermal model + temperature power-derating for a pack.

    Heat is generated by the pack's internal resistance (I^2R), referred to an
    assumed nominal bus voltage, and removed by Newtonian cooling to ambient.
    Above `derate_start_c` the usable discharge/charge power ramps down linearly
    to `floor_fraction` at `derate_end_c`, modelling battery-management thermal
    protection. All defaults are representative of a ~20 kWh LFP traction pack.
    """

    nominal_voltage_v: float = 350.0
    internal_resistance_ohm: float = 0.05
    thermal_mass_j_per_k: float = 90_000.0   # ~100 kg pack, c~900 J/kg.K
    cooling_w_per_k: float = 80.0            # conduction to coolant/ambient
    ambient_temp_c: float = 25.0
    initial_temp_c: float = 25.0
    derate_start_c: float = 45.0
    derate_end_c: float = 60.0
    floor_fraction: float = 0.30             # residual power authority when hot



@dataclass(frozen=True)
class VehicleConfig:
    """Longitudinal road-load model parameters."""

    mass_kg: float
    drag_coefficient: float
    frontal_area_m2: float
    rolling_resistance: float
    driveline_efficiency: float  # bus -> wheel (motoring)
    regen_efficiency: float  # wheel -> bus (braking)
    aux_load_w: float  # constant accessory load on the DC bus


@dataclass(frozen=True)
class TractionConfig:
    """Traction motor + final drive, used for performance acceptance checks."""

    peak_power_w: float       # short-burst electrical power the motor accepts
    continuous_power_w: float  # sustained power (top-speed / sustained climb)
    peak_torque_nm: float     # motor peak torque (ERS traction-motor target)
    wheel_radius_m: float
    gear_ratio: float         # motor-to-wheel reduction


@dataclass(frozen=True)
class ControlConfig:
    """Unified controller tuning."""

    ev_demand_threshold_w: float  # below this filtered demand, stay in EV mode
    generation_filter_tau_s: float  # low-pass time constant for the slow loop
    soc_correction_gain_w: float  # recharge power per unit SoC error
    spike_threshold_w: float  # instantaneous demand above this forces engine on
    buffer_soc_target: float = 0.7  # keep the rotors this full when refilling


@dataclass(frozen=True)
class TwinConfig:
    """Top-level configuration bundling every subsystem."""

    name: str
    atpe: ATPEConfig
    buffer: BufferConfig
    battery: BatteryConfig
    vehicle: VehicleConfig
    control: ControlConfig
    traction: TractionConfig


# --- Convenience builders ---------------------------------------------------

KWH_TO_J = 3.6e6
KW = 1_000.0


@dataclass(frozen=True)
class BodyStyle:
    """A vehicle body wrapped around the shared Phase-1 powertrain.

    Only the chassis-dependent parameters change between body styles; the ATPE
    stack, inertial buffer, battery, and control law are identical. This lets
    the twin show how the *same* powertrain behaves in different vehicle types.
    """

    name: str
    mass_kg: float
    drag_coefficient: float
    frontal_area_m2: float
    rolling_resistance: float
    wheel_radius_m: float
    driveline_efficiency: float  # AWD loses more than FWD/RWD
    aux_load_w: float
    motor_peak_kw: float = 150.0  # traction-motor peak power for this body


# Primary target is the AWD SUV (index 0); the rest are comparison bodies that
# reuse the identical Phase-1 powertrain. Aero/mass figures are representative
# real-world values for each class. The heavy SUV and pickup carry a 160 kW
# motor (vs the 150 kW class default) to clear their class targets - sized by
# acceptance.recommend_motor(); see docs/09 section 9.
PHASE1_BODIES: tuple[BodyStyle, ...] = (
    BodyStyle("AWD SUV",   mass_kg=2200, drag_coefficient=0.34, frontal_area_m2=2.8,
              rolling_resistance=0.012, wheel_radius_m=0.34, driveline_efficiency=0.92,
              aux_load_w=500, motor_peak_kw=160),
    BodyStyle("Sedan",     mass_kg=1650, drag_coefficient=0.27, frontal_area_m2=2.2,
              rolling_resistance=0.010, wheel_radius_m=0.32, driveline_efficiency=0.94,
              aux_load_w=450),
    BodyStyle("Hatchback", mass_kg=1400, drag_coefficient=0.30, frontal_area_m2=2.1,
              rolling_resistance=0.010, wheel_radius_m=0.30, driveline_efficiency=0.94,
              aux_load_w=400),
    BodyStyle("Crossover", mass_kg=1850, drag_coefficient=0.31, frontal_area_m2=2.5,
              rolling_resistance=0.011, wheel_radius_m=0.33, driveline_efficiency=0.93,
              aux_load_w=500),
    BodyStyle("Pickup",    mass_kg=2500, drag_coefficient=0.42, frontal_area_m2=3.2,
              rolling_resistance=0.013, wheel_radius_m=0.37, driveline_efficiency=0.91,
              aux_load_w=550, motor_peak_kw=160),
    BodyStyle("Van / MPV", mass_kg=2300, drag_coefficient=0.33, frontal_area_m2=3.4,
              rolling_resistance=0.012, wheel_radius_m=0.34, driveline_efficiency=0.93,
              aux_load_w=550),
)


def _phase1_powertrain() -> tuple[ATPEConfig, BufferConfig, BatteryConfig, ControlConfig]:
    """Shared Phase-1 powertrain (engine, buffer, battery, control)."""
    atpe = ATPEConfig(
        tiers=(
            TierSpec("Tier 1 (micro)", units=4, displacement_cc=100,
                     max_electric_w=30 * KW, thermal_efficiency=0.44),
            TierSpec("Tier 2 (medium)", units=2, displacement_cc=300,
                     max_electric_w=80 * KW, thermal_efficiency=0.41),
            TierSpec("Tier 3 (large)", units=2, displacement_cc=750,
                     max_electric_w=120 * KW, thermal_efficiency=0.38),
        )
    )
    buffer = BufferConfig(
        # 118 kJ = sum 1/2 I w^2 for rotors I=[0.12,0.15,0.10] kg.m^2 at 800 rad/s
        # (whitepaper illustrative sizing; see docs/10 section 4).
        max_energy_j=118_000,  # 118 kJ
        max_discharge_w=90 * KW,   # 3 rotors x ~30 kW per-MG continuous
        max_charge_w=90 * KW,
        round_trip_efficiency=0.80,  # within whitepaper's 75-85% target band
    )
    battery = BatteryConfig(
        usable_capacity_j=20 * KWH_TO_J,  # 20 kWh
        max_discharge_w=120 * KW,
        max_charge_w=80 * KW,
        soc_target=0.55,
        soc_ev_floor=0.25,
        initial_soc=0.8,
        cycle_life_efc=4000.0,  # LFP rating to ~80% capacity (derived metric only)
    )
    control = ControlConfig(
        ev_demand_threshold_w=30 * KW,
        generation_filter_tau_s=5.0,
        soc_correction_gain_w=300 * KW,  # full recharge authority at large SoC error
        spike_threshold_w=70 * KW,
    )
    return atpe, buffer, battery, control


def phase1_config_for(body: BodyStyle, rotor_coupled: bool = False) -> TwinConfig:
    """Phase-1 powertrain dropped into a specific vehicle body.

    When `rotor_coupled` is True, the inertial buffer gains a brief-burst
    discharge rating derived from the PCMRITMS rotor model (see
    pcmritms_coupling); otherwise the buffer uses its continuous rating only.
    """
    atpe, buffer, battery, control = _phase1_powertrain()
    if rotor_coupled:
        # Imported lazily to avoid a config <-> coupling import cycle.
        from .pcmritms_coupling import couple_buffer
        buffer = couple_buffer(buffer)
    vehicle = VehicleConfig(
        mass_kg=body.mass_kg,
        drag_coefficient=body.drag_coefficient,
        frontal_area_m2=body.frontal_area_m2,
        rolling_resistance=body.rolling_resistance,
        driveline_efficiency=body.driveline_efficiency,
        regen_efficiency=0.70,
        aux_load_w=body.aux_load_w,
    )
    traction = TractionConfig(
        peak_power_w=body.motor_peak_kw * KW,
        continuous_power_w=110 * KW,
        peak_torque_nm=380,
        wheel_radius_m=body.wheel_radius_m,
        gear_ratio=9.0,
    )
    return TwinConfig(f"Phase-1 {body.name}", atpe, buffer, battery, vehicle,
                      control, traction)


def phase1_config(rotor_coupled: bool = False) -> TwinConfig:
    """Phase-1 petrol AWD SUV - the primary reference vehicle (matches docs/07)."""
    return phase1_config_for(PHASE1_BODIES[0], rotor_coupled=rotor_coupled)


def phase1_variants(rotor_coupled: bool = False) -> dict[str, TwinConfig]:
    """All Phase-1 body variants keyed by name (AWD SUV first)."""
    return {b.name: phase1_config_for(b, rotor_coupled=rotor_coupled)
            for b in PHASE1_BODIES}


def with_gate1(
    cfg: TwinConfig,
    enabled: bool = True,
    prefer_cantera: bool = False,
    reference_speed_rpm: float = 2600.0,
) -> TwinConfig:
    """Return a copy of `cfg` with the Gate 1 single-cylinder model enabled.

    Opt-in so validated fuel figures from the default tier-efficiency tables
    are never disturbed unless explicitly requested (e.g. dashboard demos).
    """
    from dataclasses import replace
    gate1 = SingleCylinderGate1Config(
        enabled=enabled,
        prefer_cantera=prefer_cantera,
        reference_speed_rpm=reference_speed_rpm,
    )
    return replace(cfg, atpe=replace(cfg.atpe, gate1=gate1))


def with_battery_thermal(
    cfg: TwinConfig,
    thermal: "BatteryThermalConfig | None" = None,
) -> TwinConfig:
    """Return a copy of `cfg` with the battery lumped-thermal model enabled.

    Defaults to the representative `BatteryThermalConfig`. Opt-in so the
    validated thermodynamically-ideal figures are never disturbed.
    """
    from dataclasses import replace
    thermal = thermal or BatteryThermalConfig()
    return replace(cfg, battery=replace(cfg.battery, thermal=thermal))


def phase2_config() -> TwinConfig:
    """Phase-2 performance configuration (scaled tuples, same control law)."""
    atpe = ATPEConfig(
        tiers=(
            TierSpec("Tier 1 (micro)", units=4, displacement_cc=100,
                     max_electric_w=30 * KW, thermal_efficiency=0.44),
            TierSpec("Tier 2 (medium)", units=2, displacement_cc=350,
                     max_electric_w=100 * KW, thermal_efficiency=0.41),
            TierSpec("Tier 3 (large)", units=4, displacement_cc=1050,
                     max_electric_w=260 * KW, thermal_efficiency=0.37),
        )
    )
    buffer = BufferConfig(
        max_energy_j=210_000,
        max_discharge_w=180 * KW,
        max_charge_w=180 * KW,
        round_trip_efficiency=0.82,
    )
    battery = BatteryConfig(
        usable_capacity_j=8 * KWH_TO_J,
        max_discharge_w=250 * KW,
        max_charge_w=150 * KW,
        soc_target=0.5,
        soc_ev_floor=0.2,
        initial_soc=0.85,
    )
    vehicle = VehicleConfig(
        mass_kg=2350,
        drag_coefficient=0.30,
        frontal_area_m2=2.6,
        rolling_resistance=0.011,
        driveline_efficiency=0.94,
        regen_efficiency=0.75,
        aux_load_w=600,
    )
    control = ControlConfig(
        ev_demand_threshold_w=40 * KW,
        generation_filter_tau_s=3.0,
        soc_correction_gain_w=500 * KW,
        spike_threshold_w=120 * KW,
    )
    traction = TractionConfig(
        peak_power_w=600 * KW,
        continuous_power_w=350 * KW,
        peak_torque_nm=1200,
        wheel_radius_m=0.35,
        gear_ratio=8.0,
    )
    return TwinConfig("Phase-2 Performance", atpe, buffer, battery, vehicle, control,
                      traction)
